import { Container, Grid, Image } from "@chakra-ui/react";
import Head from "next/head";
import React from "react";

import Auth from "../components/authentication/AuthUI";
import { logos } from "../utils/logos";

const Authenticate: React.FC = () => {
  return (
    <>
      <Head>
        <title>SkyQuick</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href={logos.light} />
      </Head>
      <Container maxW="100%" h="100vh" bg={"blackAlpha.900"}>
        <Container maxW="95%" h="100vh" bg={"blackAlpha.400"} minH="100vh">
          <Grid
            templateColumns={{ base: "1fr", md: "25% 75%" }}
            gap={5}
            h="100vh">
            <Image
              src={logos.light}
              alt="SkyQuick Logo"
              w="100%"
              h="100%"
              objectFit="contain"
            />
            <Auth />
          </Grid>
        </Container>
      </Container>
    </>
  );
};
export default Authenticate;
