import { Container, useColorModeValue, Flex, Grid } from "@chakra-ui/react";
import Head from "next/head";
import Sidebar from "../components/Sidebar";
import { logos } from "../utils/logos";
import Chat from "../components/Chat";

export default function Home() {
  return (
    <>
      <Head>
        <title>SkyQuick</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href={logos.light} />
      </Head>
      <Container maxW="100%" h="100vh" bg={"blackAlpha.900"}>
        <Container maxW="95%" h="100vh" bg={"blackAlpha.100"} minH="100vh">
          <Grid templateColumns={{ base: "1fr", md: "25% 75%" }} h="100vh">
            <Sidebar />
            <Chat />
          </Grid>
        </Container>
      </Container>
    </>
  );
}
