import Head from "next/head";
import React from "react";

import Dashboard from "../components/dashboard";
import { logos } from "../utils/logos";

const Home: React.FC = () => {
  return (
    <>
      <Head>
        <title>SkyQuick</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href={logos.light} />
      </Head>
      <Dashboard />
    </>
  );
};

export default Home;
